openshift/file-integrity-operator

cmd/manager/main.go
go.mod
pkg/apis/addtoscheme_fileintegrity_v1alpha1.go
pkg/controller/add_configmap.go
pkg/controller/add_fileintegrity.go
pkg/controller/configmap/configmap_controller.go
pkg/controller/fileintegrity/fileintegrity_controller.go
tests/e2e/e2e_test.go
tests/e2e/helpers.go

These were pointing to mrgogers950 repo.

Change references to old repo to the openshift org

---

Makefile

This enhances the makefile to match what we have on the
compliance-operator:
* Help target
* e2e with image upload
* opreator-sdk download
* image build

Enhance Makefile to match compliance-operator

---

Makefile

This reverts commit 4d9808a453f57007a06f51a2a7896c14cbd23091.

Revert "Add GOPROXY and GOSUMDB to operator-sdk call"

---

deploy/operator.yaml

schedule operator to run on masters

---

tests/e2e/e2e_test.go

Rather than polling to check if we transitioned to Initializing and back during config updates, we just poll for Active status and the configMap result that we expect.

e2e: poll for configMap changes instead of status

---

Makefile
images/aide/Dockerfile
images/aide/Dockerfile.ci

images: add aide dockerfiles and make target

---

tests/e2e/e2e_test.go
tests/e2e/helpers.go

Move all resource cleanup to cleanUp(). This gives us more control over ordering.
Fixes https://github.com/openshift/file-integrity-operator/issues/31

e2e: reorder cleanup

---

Makefile
README.md
deploy/olm-catalog/file-integrity-operator/0.1.0/file-integrity-operator.v0.1.0.clusterserviceversion.yaml
deploy/olm-catalog/file-integrity-operator/0.1.0/file-integrity.openshift.io_fileintegrities_crd.yaml
deploy/olm-catalog/file-integrity-operator/file-integrity-operator.package.yaml
deploy/olm-catalog/operator-source.yaml

Generated using `$ operator-sdk olm-catalog gen-csv --csv-version "0.1.0"`

Generate CSV for OLM

---

pkg/controller/fileintegrity/config_defaults.go
pkg/controller/fileintegrity/fileintegrity_controller.go
tests/e2e/e2e_test.go
tests/e2e/helpers.go

This depends on https://github.com/openshift/file-integrity-operator/pull/28 and https://github.com/openshift/file-integrity-operator/pull/32. Pushing as a WIP at the moment.

e2e logcollector tests

---

Makefile

Currently, we're using the references from the quay image repo to run
the workloads spawn by the compliance-operator in the e2e tests. This is
not ideal since we can't test so easily any changes we do to the
workloads (e.g. resultscollector and resultserver).
This enables that by changing the references to the workloads in the
deploy/operator.yaml, which is what operator-sdk uses to deploy the
operator

Test newly built workload images in e2e tests

---

pkg/controller/configmap/configmap_controller.go

Triggering a rolling update to re-initialize the AIDE pods can take some time.
Delete the DS pods instead. 
Trying this out with CI

Delete DS pods instead of triggering a rolling update

---

pkg/controller/fileintegrity/fileintegrity_controller.go

This part bothered me so I untangled it.

Refactor user configMap reconcile steps

---

deploy/role.yaml
deploy/role_binding.yaml

This gives us less resources to manage as well as fixing an issue with the generated CSV.

Move scc role

---

Makefile

@JAORMX this catches the Makefile up with compliance-operator's changes.

Add make release targets

---

pkg/common/util.go
pkg/controller/configmap/configmap_controller.go
pkg/controller/fileintegrity/config_defaults.go

Please check out the commit messages for more details.

Fix several race conditions in the FI operator

---

Makefile

This will come in handy when using go routines.

Build with data race detection by default

---

README.md

Accidentally left this change out of the last PR.
@JAORMX

README update correction

---

Dockerfile.ocp
images/aide/Dockerfile.ocp

Staging these so I can submit the RH build system request. We'll get build results confirmed before the request gets resolved, so I might need to iterate on them.

Add initial downstream Dockerfiles

---

OWNERS

This is a downstream build requirement.

Add bugzilla component to OWNERS

---

Dockerfile.ocp

Changing this to sync it with https://github.com/openshift/file-integrity-operator/pull/72

Update release dockerfile

---

README.md
pkg/controller/fileintegrity/fileintegrity_controller.go
tests/e2e/e2e_test.go

https://issues.redhat.com/browse/OCPBUGSM-1054

Re-apply default config when unsetting spec.config

---

README.md

I wasn't happy with some of the original wording, also added advice for selecting a digest type in a custom config for https://bugzilla.redhat.com/show_bug.cgi?id=1829285

README: Edit configuration section

---

README.md

https://bugzilla.redhat.com/show_bug.cgi?id=1823653

README: Add a note about cm ownership

---

cmd/manager/logcollector.go

https://bugzilla.redhat.com/show_bug.cgi?id=1869293

Move OK configMap log to debug level

---

README.md

After merging, I'll fast forward rhaos-4.6-rhel-8 branch to test the downstream sync.

README change to test downstream sync

---

Makefile

These targets are useful for development.

Add deploy, deploy-local and tear-down targets to Makefile

---

Dockerfile.ci
Dockerfile.ocp
build/Dockerfile
images/aide/Dockerfile
images/aide/Dockerfile.ci
images/aide/Dockerfile.ocp

Update container image bases

---

README.md

Some more information about deletion of FI and manually re-initializing

Bug 1866805: Add notes to README

---

Makefile
cmd/manager/logcollector.go
tests/e2e/e2e_test.go
tests/e2e/helpers.go

Also adding a commit to capture daemon logs in the E2E, same code as compliance-operator.

Bug 1869293: Add timestamp to daemon logs

---

Makefile

There were two make targets that were doing essentially the same thing.
In order to not break command line workflow, I kept the old one around,
just made it call the newer one. I chose the keep the newer one becase
we also have the same target name in CO and it makes sense to be
consistent.

Reduce code-duplication in Makefile

---

Makefile

make: Download the opm binary

---

pkg/controller/fileintegrity/fileintegrity_controller.go
pkg/controller/node/node_controller.go
tests/e2e/e2e_test.go
tests/e2e/helpers.go

They just help to control my OCD.

Several small cleanup patches

---

README.md

The default is not an hour, but 15 mins.

Fix gracePeriod documentation

---

pkg/controller/fileintegrity/fileintegrity_controller.go

We were not taking into account potential updates to the daemonset's
image. This fixes that by handling that in the reconcile loop.

Handle daemon updates

---

deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml

* This is no longer built with `-race` so it reduces memory consumption.

Release v0.1.9

---

pkg/controller/fileintegrity/fileintegrity_controller.go

In evaluating the File Integrity Operator for use with OpenShift Dedicated, I noticed that currently, the FIO looks like it creates a daemonSet from a fileIntegrity CRD, but does not update the daemonSet nodeSelector when the fileIntegrity nodeSelector is changed.  This is somewhat confusing to users (at least myself) and not how folks would expect it to behave. Especially within OSD, our use of syncSets to manage operator resources would mean it would be difficult to patch or change fileIntegrity objects - we'd have to have hive remove them, wait, then recreate a new one.
This change adds a check to the fileIntegrity reconcile loop for changes to the fileIntegrity nodeSelectors and updates the daemonSet if there is a change.
Example: 
```
$ oc create -f - <<< …
```

Adds reconcile for nodeSelector changes

---

deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml
deploy/olm-catalog/file-integrity-operator/manifests/fileintegrity.openshift.io_fileintegrities_crd.yaml
deploy/olm-catalog/file-integrity-operator/manifests/fileintegrity.openshift.io_fileintegritynodestatuses_crd.yaml

* Includes fixes to nodeSelector/tolerations updates
* status display enhancements

Release v0.1.10

---

deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml

*    Adds OLM annotation that indicates that disconnected is supported.

Release v0.1.11

---

README.md
deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml

* Adds OLM annotation that allows the operator to be installed in Disconnected environments.

Backport v0.1.11

---

Dockerfile.ci
Dockerfile.ocp
images/aide/Dockerfile.ci
images/logcollector/Dockerfile.ci

The other registry is being decommissioned so we need to update.
Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>

Update container registry to registry.ci.openshift.org

---

cmd/manager/daemon.go
go.mod
pkg/controller/fileintegrity/fileintegrity_controller.go
vendor/k8s.io/client-go/tools/watch/informerwatcher.go
vendor/k8s.io/client-go/tools/watch/retrywatcher.go
vendor/k8s.io/client-go/tools/watch/until.go
vendor/modules.txt

Bug 1927291: daemon: Use RetryWatcher and set GODEBUG=madvisedontneed=1

---

cmd/manager/daemon.go
go.mod
pkg/controller/fileintegrity/fileintegrity_controller.go
vendor/k8s.io/client-go/tools/watch/informerwatcher.go
vendor/k8s.io/client-go/tools/watch/retrywatcher.go
vendor/k8s.io/client-go/tools/watch/until.go
vendor/modules.txt

Bug 1925134: daemon: Use RetryWatcher and set GODEBUG=madvisedontneed=1

---

deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml

Update CSV links

---

deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml

This release fixes the image references in the 0.1.14 release that were included by mistake.

Release v0.1.15

---

CHANGELOG.md
Makefile
utils/update_changelog.sh

Add an initial CHANGELOG.md and make changelog target

---

README.md

README was still using the old instructions.

README: Fix instructions to install from OLM

---

cmd/manager/daemon.go

Just pushing what I came up with at the moment. Still need to test.

daemon: Handle SIGTERM and SIGKILL

---

pkg/common/util.go

Using a FIPS disallowed algorithm in the AIDE config under FIPS mode makes AIDE throw a 255 error code. Handle this error as a possible FIPS error, even though it could probably be encountered in some other rare case, but this would be the most informative to our user.

Bug 1966566: Handle AIDE error code 255

---

CHANGELOG.md
deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml

- Handle AIDE error code 255
- Update dependencies
- README: Fix instructions to install from OLM
- Add operator and aide-ds pod limits
- daemon: Handle SIGTERM and SIGKILL
- Add an initial CHANGELOG.md and make changelog target
- Exclude the CNI plugin directory

Release v0.1.16

---

cmd/manager/operator.go
deploy/operator.yaml
deploy/service_account.yaml

Handle metrics service during operator start

---

pkg/controller/fileintegrity/config_defaults.go
tests/e2e/helpers.go

Bug 1999186: Add MCO and CVO related config excludes

---

Makefile

Makefile: Apply monitoring resources during deploy-local

---

Makefile
pkg/controller/fileintegrity/fileintegrity_controller.go

This also adds the test-catalog targets to test an index.

Bug 2002519: Delete legacy daemonSets after upgrade

---

pkg/controller/fileintegrity/fileintegrity_controller.go

Bug 2010706: Fix nil deref in daemonSet upgrade path

---

CHANGELOG.md
deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml

- Makefile: Make image bundle depend on $TAG
- Fix nil deref in daemonSet upgrade path

Release v0.1.20

---

CHANGELOG.md
deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml

Release v0.1.22

---

deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml

Let's advertise the features we test and support through the CSV.
Jira: [CMP-1164](https://issues.redhat.com/browse/CMP-1164)

CSV: We support FIPS

---

tests/e2e/helpers.go

This allows us to fail individual e2e tests and still retain the operator logs
for each. Beforehand, we always skipped cleanup on error in order to get the
failing operator logs.

e2e: Add the operator logs to artifacts

---

CHANGELOG.md
deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml

Release v0.1.24

---

Makefile

Also add --security-opt seccomp=unconfined to the operator image build options.
This fixes building fedora-minimal:latest (35+) for buildah and newish versions of
podman (3.3).

Makefile: Add buildah as an option for RUNTIME=

---

Makefile
config/manifests/bases/file-integrity-operator.clusterserviceversion.yaml

Raising a PR for building image for ppc64le

Added code changes for image to support ppc64le

---

bundle/manifests/file-integrity-operator.clusterserviceversion.yaml
config/manifests/bases/file-integrity-operator.clusterserviceversion.yaml

- This is added to the CSV config base, also update the generated bundle contents with `make bundle`.

Add CSV support for s390x

---

Makefile

Setting CATALOG_DEPLOY_NS allows using catalog-deploy to a non-default
namespace.

Makefile: Add CATALOG_DEPLOY_NS variable for make catalog-deploy

---

tests/framework/resource.go

This should fix issues with the test namespace regarding PSP changes.

e2e: Add PSP labels to test namespace

---

Makefile

- removes an unused env variable
- fixes a misleading comment

make: Small file-based catalog cleanup

---

config/manifests/bases/file-integrity-operator.clusterserviceversion.yaml

Same as https://github.com/ComplianceAsCode/compliance-operator/pull/184

Add OpenShift subscription annotation

---

go.mod
go.sum
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
vendor/modules.txt

Addresses https://github.com/openshift/file-integrity-operator/security/dependabot/21

Update prometheus/client_golang to 1.11.1

---

go.mod
go.sum
vendor/github.com/coreos/ignition/v2/config/shared/errors/errors.go
vendor/github.com/coreos/ignition/v2/config/v3_2/types/directory.go
vendor/github.com/coreos/ignition/v2/config/v3_2/types/file.go
vendor/github.com/coreos/ignition/v2/config/v3_2/types/mode.go
vendor/github.com/spf13/pflag/flag.go
vendor/github.com/spf13/pflag/ip.go
vendor/github.com/spf13/pflag/ipnet_slice.go
vendor/github.com/spf13/pflag/string_array.go
vendor/modules.txt

Addresses https://github.com/openshift/file-integrity-operator/security/dependabot/20

Update coreos/ignition/v2 to 2.14.0

---

.github/dependabot.yml

Duplicate labels make dependabot unhappy

dependabot.yaml: Remove duplicate value

---

CHANGELOG.md
bundle/manifests/file-integrity-operator.clusterserviceversion.yaml
catalog/preamble.json
config/manifests/bases/file-integrity-operator.clusterserviceversion.yaml
version.Makefile
version/version.go

Release v1.2.1

---

OWNERS

Adding Bhargavi to the owner file.

Add Bhargavi as reviewer

---

Dockerfile.ci
build/Dockerfile

Let's us a version of golang that contains a patched version of
net/http.
https://github.com/golang/go/issues/63426

Use golang 1.20

---

build/Dockerfile.openshift

Add initial Containerfile to build the File Integrity Operator in Konflux.

Add operator Containerfile for Konflux

---

.tekton/file-integrity-operator-pull-request.yaml
.tekton/file-integrity-operator-push.yaml

Enable Power and Z builds via Konflux

Enable Power and Z builds for FIO in Konflux

---

.tekton/file-integrity-operator-bundle-release-1-3-pull-request.yaml
.tekton/file-integrity-operator-bundle-release-1-3-push.yaml
.tekton/file-integrity-operator-release-1-3-pull-request.yaml
.tekton/file-integrity-operator-release-1-3-push.yaml

This was missed in https://github.com/openshift/file-integrity-operator/pull/687

Fix output image value for Y-stream repos

---

.tekton/file-integrity-operator-bundle-dev-pull-request.yaml
.tekton/file-integrity-operator-bundle-dev-push.yaml
.tekton/file-integrity-operator-dev-pull-request.yaml
.tekton/file-integrity-operator-dev-push.yaml
bundle-hack/update_csv.go

We are renaming the master application to dev, and need to update the bundle script and konflux pipeline config to adapt it.

Update konflux config and update script for dev application
