- Dockerfile.ci
Similarly to the one we added for the compliance-operator, this adds a
dockerfile for CI use only.
> Add Dockerfile for CI usage

- tests/e2e/helpers.go
Currently we have a waiting time of 2 minutes for the creation of stuff
(e.g. the operator itself). This might be too short in cases where we
need to fetch the image for the first time. So, similarly as with the
compliance-operator, lets up this to 10min.
> Up timeout for cleanup and wait

- Makefile
This will ensure that we use golang.org's proxy instead of relying
directly on github.
> Add GOPROXY and GOSUMDB to our go invocation

- deploy/crds/file-integrity.openshift.io_fileintegrities_crd.yaml
- pkg/apis/fileintegrity/v1alpha1/fileintegrity_types.go
- pkg/apis/fileintegrity/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/fileintegrity/v1alpha1/zz_generated.openapi.go
- pkg/common/util.go
- pkg/controller/add_status.go
- pkg/controller/configmap/configmap_controller.go
- pkg/controller/fileintegrity/config.go
- pkg/controller/status/status_controller.go
- tests/e2e/e2e_test.go
This adds a Phase field to FileIntegrityStatus and a controller to manage it. The phases are
* Initializing - The file integrity checking is initializing: The controller sets this when the re-initialization daemonSet exists (upon config change), or the AIDE runner daemonSet is not totally ready.
* Active - The file integrity checking is currently active: The controller sets this when the AIDE runner daemonSet has available pods on all nodes.
* Inactive - There is no active integrity checking: The controller sets this when the AIDE runner daemonSet does not exist.
The controller reconciles every 30 seconds. The reason there is a continuous reconcile loop is because there is no informer action triggered by a daemonSet status update, which is what the controller monitors for status changes. …
> Add FileIntegrityStatus controller

- Makefile
This is meant to check to if we'll need to rename kubeadmin. However,
given that it's positioned on the ifeq call. It gets called every
time.
This doesn't actually cause an error but it can be very distracting. So
lets get rid of the standard error of this command.
> Redirect output of `oc whoami`

- pkg/controller/fileintegrity/config_defaults.go
- pkg/controller/fileintegrity/fileintegrity_controller.go
- tests/e2e/e2e_test.go
- tests/e2e/helpers.go
This test just ensures there's no re-init when you specify a nonexistant AIDE configmap, plus some refactoring.
> add an e2e test for a missing AIDE configmap

- tests/e2e/helpers.go
The initialization stage is taking too long for some reason. Lets pu the
timeout to 15 min to reduce the errors in CI while we fix this.
> Up timeout to 15 min

- deploy/operator.yaml
This makes a in-cluster deployment easier with `make image-to-cluster`
> deploy: change operator image to internal repo

- pkg/common/constants.go
- pkg/common/util.go
- pkg/controller/configmap/configmap_controller.go
- pkg/controller/fileintegrity/fileintegrity_controller.go
- pkg/controller/status/status_controller.go
- tests/e2e/e2e_test.go
This ties the AIDE ConfigMap to the FileIntegrity object by giving them
the same name. Effectively, this ends up making the configurations
unique per file-integrity object, as opposed to relying on a single
ConfigMap.
This is the first step on enabling us to use multiple FileIntegrities
per deployment (which would ideally serve different node sets).
Given that the name of the config file matches the name of the
FileIntegrity, we can infer the DaemonSet name from it. Which are also
now unique per CR instance.
> Tie AIDE config to FileIntegrity Object

- deploy/operator.yaml
- pkg/controller/fileintegrity/fileintegrity_controller.go
- pkg/controller/fileintegrity/utils.go
This allows us to set the workload images through environment variables,
like we do for the compliance-operator.
> Allow setting workload images through environment variables

- pkg/controller/fileintegrity/config_defaults.go
Files under /etc/kubernetes/manifests/ can be changed by the cluster-kube-apiserver-operator during normal use, so add this directory to the default policy.
> Exclude /etc/kubernetes/manifests from default AIDE policy

- pkg/controller/fileintegrity/config_defaults.go
- tests/e2e/helpers.go
Using /etc/kubernetes/cloud.conf for this test was causing problems, so modify
it to an innocuous change (a comment) to a file we know will always exist on
the node (resolv.conf).
Additionally, update the test config so the config change test remains
accurate.
> e2e: Change modify file path

- Makefile
This one was missing the tag. And this is needed for pushing a release.
> Explicitly set image tag when building operator image

- Makefile
Currently we're getting a deprecation warning:
[Deprecation notice] The 'operator-sdk generate openapi' command is deprecated!
- To generate CRDs, use 'operator-sdk generate crds'.
- To generate Go OpenAPI code, use 'openapi-gen'. For example:
which ./bin/openapi-gen > /dev/null || go build -o ./bin/openapi-gen k8s.io/kube-openapi/cmd/openapi-gen
./bin/openapi-gen --logtostderr=true -o "" -i ./pkg/apis/<group>/<version> -O zz_generated.openapi -p ./pkg/apis/<group>/<version> -h ./hack/boilerplate.go.txt -r "-"
> make: Drop deprecated operator-sdk generate openapi, use generate crds instead

- tests/e2e/e2e_test.go
- tests/e2e/helpers.go
The re-init e2e test was only verifying that the FileIntegrity is
Active. But this is not enough. We also need to verify that the nodes
are in a good state (Succeeded) after the database has been
re-initialized.
> reinit e2e: Test that nodes are in good state after re-init

- pkg/controller/node/node_controller.go
- tests/e2e/e2e_test.go
- tests/e2e/helpers.go
- vendor/github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/install.go
- vendor/modules.txt
Please see the commit messages for more details, mostly this PR makes the
holdoff pods code work as it makes the configmap names consistent across the
code and fixes some other issues with the pod or the scripts they use.
In addition, I wonder if the controller shouldn't remove the pods when they
are done? Also I guess tests should be improved since they didn't catch
the issues the firts time around?
> Node controller: Several fixes

- pkg/controller/fileintegrity/config_defaults.go
- tests/e2e/helpers.go
This is just so there's no confusion about which checksums are in use.
> Remove unused groups from AIDE config

- pkg/common/constants.go
- pkg/controller/fileintegrity/config_defaults.go
- pkg/controller/fileintegrity/fileintegrity_controller.go
Using container images from a public registry migth break disconnected
installs.
> FI: Don't use a third-party container image

- cmd/manager/logcollector.go
- deploy/crds/file-integrity.openshift.io_fileintegrities_crd.yaml
- deploy/crds/file-integrity.openshift.io_v1alpha1_fileintegrity_cr.yaml
- pkg/apis/fileintegrity/v1alpha1/fileintegrity_types.go
- pkg/common/constants.go
- pkg/common/util.go
- pkg/controller/configmap/configmap_controller.go
- pkg/controller/fileintegrity/config_defaults.go
- pkg/controller/fileintegrity/fileintegrity_controller.go
- tests/e2e/e2e_test.go
- tests/e2e/helpers.go
FI ctrl: Make debugging of the aggregator configurable
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The aggregator pod can optionally produce some debug information, but the
debug flag was hardcoded to false. This patch extends the FileIntegritySpec
struture with a new field, debug, that defaults to false. The admin can
enable debugging of the logcollector by setting the debug flag to true.
FI ctrl: Don't set the timeout explicitly
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Setting the timeout explicitly or even making the timeout configurable is 
not really needed, because if the timeout occurs, the loop that waits for
the files the aggregator is watching simply takes another iteration.
FI ctrl: Make the interval configurable
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Extends the …
> FI controller: Make the interval and the debug flag configurable

- Dockerfile.ci
- build/Dockerfile
- cmd/manager/daemon.go
- cmd/manager/logcollector.go
- cmd/manager/main.go
- pkg/common/constants.go
- pkg/common/util.go
- pkg/controller/configmap/configmap_controller.go
- pkg/controller/fileintegrity/config_defaults.go
- pkg/controller/fileintegrity/fileintegrity_controller.go
- pkg/controller/node/node_controller.go
- tests/e2e/e2e_test.go
- tests/e2e/helpers.go
This PR makes for a simpler AIDE daemonSet by combining the logcollector, aide check, and re-init functionality into a single go daemon. Aside from the needed e2e changes, I revised some logging statements in order to give a clearer flow between controllers particularly during re-initialization, as well as adding code to handle configuration changes from an existing FI  (see updateDaemonSetPodArgs()).
> Revised AIDE daemonSet

- cmd/manager/daemon.go
- cmd/manager/logcollector.go
This reduces the code a little bit and makes the log collector and aide
loop have their synchronization dependent on whether there's a result or
not.
This way, the only "sleep" is done in the aide loop, and the log
collector will only collect if there is indeed a result ready.
> daemon: Change result handling to use channels instead of mutexes

- cmd/manager/daemon.go
The current implementation (as well as the previous one based on
mutexes) makes the daemon run in still a sort of serial manner.
The channel added a more go-friendly behavior to the go routines, by
handling shared structures through message passing. However, it's still
fairly serial. Both go-routines (the aide check and the log collector)
will be blocked until both are ready for receiving messages.
Introducing a buffered channel enables us to deal with this in a more
elegant way.
The sender (the aide check go routine) will be able to send and continue
to loop as long as there's cycles in the channel.
The receiver will be blocked until there are messages to receive.
This way, the main "blocking point" is the aide checker, which is the
one that sleeps with a grace period, and that will be …
> Use buffered channel for results in daemon

- Makefile
- README.md
- deploy/crds/fileintegrity.openshift.io_fileintegrities_crd.yaml
- pkg/apis/fileintegrity/v1alpha1/fileintegrity_types.go
- pkg/apis/fileintegrity/v1alpha1/zz_generated.deepcopy.go
- pkg/controller/fileintegrity/fileintegrity_controller.go
- tests/e2e/e2e_test.go
- tests/e2e/helpers.go
Add a `tolerations` field to FileIntegritySpec, allowing running on nodes with
custom taints. Defaults to master node tolerations.
> Enable tolerations for fileIntegrity

- Makefile
- deploy/operator.yaml
- pkg/common/util.go
The RHBS digest pinning feature relies on RELATED_IMAGE_* variables to do image reference substitution.
@jhrozek
> Rename image env variables for downstream

- deploy/role.yaml
- deploy/role_binding.yaml
- deploy/service_account.yaml
- pkg/common/constants.go
This creates a service account and a role specific for the daemon,
ensuring that it only runs with the minimal set of permissions it needs.
> Use own role and service account for daemon

- tests/e2e/e2e_test.go
- tests/e2e/helpers.go
This also removes the leftover sleeps.
> e2e: Make tests resilient to status flapping

- README.md
- deploy/crds/fileintegrity.openshift.io_fileintegrities_crd.yaml
- pkg/apis/fileintegrity/v1alpha1/fileintegrity_types.go
- pkg/common/constants.go
- tests/e2e/e2e_test.go
- tests/e2e/helpers.go
The AIDE integrity checking is a very intensive process, with our
current default of 10s, the daemon would constantly take ~2.2G of memory
(for each instance... meaning, in each node).
This is excessive and will certainly raise alarms with folks running
this in production.
I propose to set our default grace period to be 900 (15 min), which
will result in the daemonsets taking 60MB when idle, and having usage
spikes every 15 mins.
> Make default grace period to be 15 min

- deploy/crds/fileintegrity.openshift.io_fileintegrities_crd.yaml
- pkg/apis/fileintegrity/v1alpha1/fileintegrity_types.go
Wording suggestions welcome, in general having the strings available for oc explain increases usability.
> api: Add description to spec.config keys to enable oc explain

- cmd/manager/logcollector.go
- pkg/common/constants.go
- pkg/common/util.go
- pkg/controller/configmap/configmap_controller.go
- pkg/controller/fileintegrity/fileintegrity_controller.go
Renames common.IntegrityConfigMapOwnerLabelKey to a more generic names and
subsequently uses the the label for DS, pods and the resulting
FileIntegrityNodeStatus objects.
This way, the admin can easily list objects that relate to a single FI
object.
> FI: Label the DS, pods and FileIntegrityNodeStatus with owner label

- cmd/manager/daemon.go
Especially in the case the watch command fails, the watcher variable
would have been nil and while we write to the exit channel to signal
that the daemon should quit, we would still continue in the
integrityInstanceLoop goroutine and potentially dereference the nil
value.
Let's cleanly exit from the goroutine instead.
> daemon: Shortcut the integrityInstanceLoop if a watch can't be found

- Dockerfile.ci
- cmd/manager/logcollector.go
- deploy/olm-catalog/file-integrity-operator/0.1.5/file-integrity-operator.v0.1.5.clusterserviceversion.yaml
This file is sourced for the downstream bundle builds now. Since the downstream bundle builds specify a single release it errors out on the replaces: line.
> Remove replaces: from CSV

- cmd/manager/daemon.go
- deploy/crds/fileintegrity.openshift.io_fileintegritynodestatuses_crd.yaml
- pkg/apis/fileintegrity/v1alpha1/fileintegrity_types.go
- pkg/apis/fileintegrity/v1alpha1/zz_generated.deepcopy.go
- pkg/common/util.go
- pkg/controller/configmap/configmap_controller.go
- pkg/controller/status/status_controller.go
- tests/e2e/e2e_test.go
- tests/e2e/helpers.go
In case the configuration was wrong, the reinitLoop function would just
continue its loop, but because each loop tries to acquire the aideFiles
mutex, subsequent loops would just deadlock waiting on a mutex they
locked themselves.
To make sure the admin is notified about this, we watch for aide error conditions and put their string representation as a result to the fileIntegrityNodeStatus.
The fileIntegrityNodeStatus API is also extended with a lastResult attribute. This is the Result attribute with the latest timestamp. The reason I added the new attribute is that 1) it is easier this way to check if the "current" status is an error which is what the next patch does and 2) it will be useful in order to provide custom column printers
Finally, the status controller is extended so that if …
> Bug 1826301: Mark the nodeStatus and the FI object as Error in case the config can't even be loaded

- tests/e2e/helpers.go
In cases where setting the node's taint fails, we should be more
resilient and try again.
> e2e: Be more resilient when setting node taints

- pkg/controller/fileintegrity/cm_to_fi_mapper.go
- pkg/controller/fileintegrity/fileintegrity_controller.go
- tests/e2e/e2e_test.go
- tests/e2e/helpers.go
The FI controller used to only watch for FI object changes. That meant
that if the configMap pointed to by spec.config changed, the operator
would not re-render the configuration the DS uses until the FI object
was 'touched'.
This patch uses a custom mapper to reconcile FI objects when CMs that
are used by a FI changes.
> Reload FI when the configMap the FI points to changes

- Makefile
CI is using its own namespace and the Makefile isn't ready for it.
> Disable custom namespace in Makefile

- README.md
Fix typo in YAML. integrtiy -> integrity
configMap and fileIntegrity are names of CRDs and 
should be capitalized to match the CRD name
> Fix some typos in the README.md file

- Makefile
- build/Dockerfile
- images/aide/Dockerfile
The dev workflow to deploy to a local cluster is broken. This fixes that.
* Non-kubeadmin users were not able to deploy
* We were not using a registry explicitly (podman needs it)
This also fixes the release process to use skipRange, similar to
what we did in the compliance-operator.
> Fix dev deployments in local clusters

- Makefile
The overhead is not worth it.
Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>
> Remove `-race` flag from manager build

- deploy/crds/fileintegrity.openshift.io_fileintegritynodestatuses_crd.yaml
- deploy/olm-catalog/file-integrity-operator/manifests/fileintegrity.openshift.io_fileintegrities_crd.yaml
- deploy/olm-catalog/file-integrity-operator/manifests/fileintegrity.openshift.io_fileintegritynodestatuses_crd.yaml
- pkg/apis/fileintegrity/v1alpha1/fileintegrity_types.go
This shows the latest status for a node: 
```
$ oc get fileintegritynodestatuses                                                       
NAME                                                NODE                          STATUS
example-fileintegrity-ip-10-0-128-75.ec2.internal   ip-10-0-128-75.ec2.internal   Succeeded
```
> Bug 1921692: Add status columns to fileintegritynodestatus output

- pkg/controller/fileintegrity/fileintegrity_controller.go
- tests/e2e/e2e_test.go
If the `nodeSelector` or `tolerations` sections of the `FileIntegrity` object were updated, these changes wouldn't reflect on the resulting operand (the DaemonSet). This fixes that.
Extra logging is added to be able to debug what is being updated.
> Bug 1923096: Update nodeSelector and Tolerations

- deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml
This is to advertise disconnected support per https://docs.openshift.com/container-platform/4.6/operators/operator_sdk/osdk-generating-csvs.html#olm-enabling-operator-for-restricted-network_osdk-generating-csvs
> Add Disconnected support annotation to CSV

- deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml
This enables the label `operatorframework.io/cluster-monitoring: "true"`
in the ClusterServiceVersion. This will enable automatic monitoring
setup in the namespace. [1]
[1] https://github.com/openshift/enhancements/blob/master/enhancements/olm/olm-managed-operator-metrics.md
Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>
> Enable OCP-provided monitoring services

- build/Dockerfile
- cmd/manager/daemon.go
- pkg/controller/fileintegrity/fileintegrity_controller.go
- Add local, pprof(heap), and aide config/data path options to the AIDE daemon to
allow running standalone.
- Change default mount path of the aide config for the daemonSet to /config.
This leaves /tmp available as an EmptyDir mount needed for pprof.
- Add golang to build/Dockerfile for running pprof in a Pod exec command.
> daemon: Changes for running with pprof

- README.md
Adds a note to the README.md section on comression of AIDE logs to indicate the presense of the `file-integrity.openshift.io/compressed` annotation if the logs are compressed. This annotation will be helpful in determining with automation if the logs are compressed or not.
Signed-off-by: Christopher Collins <collins.christopher@gmail.com>
> Adds note about configMap annotation indicating compression of AIDE logs

- cmd/manager/daemon.go
- go.mod
- pkg/controller/fileintegrity/fileintegrity_controller.go
- vendor/k8s.io/client-go/tools/watch/informerwatcher.go
- vendor/k8s.io/client-go/tools/watch/retrywatcher.go
- vendor/k8s.io/client-go/tools/watch/until.go
- vendor/modules.txt
* Use a RetryWatcher for the FileIntegrity instance. This avoids pod restarts due to watcher timeouts.
* Set `GODEBUG=madvisedontneed=1` for pods. Without this, the go runtime holds on to cache longer, causing memory statistics reported by the cluster to appear high. Long running daemonSet pods were showing ~2Gb memory used, but it was almost all in cache by the runtime.
> Bug 1925105: daemon: Use RetryWatcher

- cmd/manager/daemon.go
- cmd/manager/logcollector.go
Instead of reading the whole file and executing operations on top of
that loaded file. This loads the reader interface on to a buffered
reader and passes that around; thus only reading the file when it's
really needed (for compression or writing).
This also removes the offset tracking, which wasn't being used since
AIDE truncates the log file before writing it.
Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>
> logcollector: Only read log once in a buffered way

- pkg/controller/fileintegrity/fileintegrity_controller.go
The option is `GODEBUG=madvdontneed=1` not `GODEBUG=madvisedontneed=1`
> Bug 1925105: Fix madvise setting

- cmd/manager/daemon.go
- cmd/manager/logcollector.go
- tests/e2e/e2e_test.go
- tests/e2e/helpers.go
* Fix a crash due to passing a nil Reader to compress().
* Create a proper status when compression is needed.
* A compressed log may still be over the limit, in which case add a warning to the configMap to fetch the log manually.
* Removes the initial AIDE result when starting up to avoid a race with the AIDE loop and re-init loop.
* Compression e2e's
> Bug 1943475: Compression fixes

- pkg/controller/fileintegrity/config_defaults.go
- tests/e2e/helpers.go
This stops /etc/kubernetes/cni/net.d/ from being covered under scans with the
default config.
> Exclude the CNI plugin directory

- deploy/operator.yaml
- pkg/controller/fileintegrity/fileintegrity_controller.go
Closes https://github.com/openshift/file-integrity-operator/issues/68
> Add operator and aide-ds pod limits

- CHANGELOG.md
- deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml
- Move test-specific permissions out of deploy manifests
- Use latest for CSV documentation link
- Enable TLS for controller metrics
- vendor deps
- Add controller-based Prometheus metrics
- Update ignition and MCO dependencies
- Update gosec and fix warnings
> Release v0.1.17

- Dockerfile.ci
- build/Dockerfile
The centos:8 one previously used was quite hefty, switch to fedora-minimal.
This uses :34 instead of :latest to avoid moving to the next version by
surprise.
> Use fedora-minimal:34 base image

- Makefile
- pkg/common/constants.go
- pkg/common/name.go
- pkg/common/util.go
- pkg/controller/configmap/configmap_controller.go
- pkg/controller/fileintegrity/fileintegrity_controller.go
- pkg/controller/node/node_controller.go
- pkg/controller/status/status_controller.go
- tests/e2e/e2e_test.go
- tests/e2e/helpers.go
Make re-init daemonSets apply to a single node at a time when going through a
node update. This fixes the issue where all nodes are re-initialized each time
a single node updates.
> Bug 1862022: Per-node reinit during update

- pkg/common/constants.go
- pkg/controller/fileintegrity/fileintegrity_controller.go
- pkg/controller/status/status_controller.go
- Use an owner label to look up relevant re-init daemonSets instead of
individually by name. This simplifies the status controller's reconcile loop.
@JAORMX @jhrozek
> Optimize per-node reinit calls

- CHANGELOG.md
- deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml
- Optimize per-node reinit calls
- Handle metrics service during operator start
- Bug 1862022: Per-node reinit during update
- Update Dockerfile.ci goland and base image
- Use fedora-minimal:34 base image
> Release v0.1.18

- README.md
- cmd/manager/operator.go
background: on a cluster with frequently changing nodes there's a lot of alert noise generated because of lingering fileintegritynodestatuses belonging to nodes that don't exist anymore.
Maybe a better approach would be to delete the fileintegritynodestatus here: https://github.com/openshift/file-integrity-operator/blob/a61147841dccfb5719f042476f144270a0d2551d/pkg/controller/node/node_controller.go#L101 (unfortunately that exceeds my read-only Golang capabilities)
> minor: adapt prometheusrule to only alert on currently existing nodes

- Makefile
IMAGE_FORMAT will be deprecated, so rename this to a variable we'll define in openshift/release
> Makefile: Rename IMAGE_FORMAT var

- CHANGELOG.md
- deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml
- Delete old aide-ds- prefixed daemonSets if they exist
- Makefile: Add test-catalog targets
- Makefile: Apply monitoring resources during deploy-local
- Makefile: Rename IMAGE_FORMAT var
- Use ClusterRole/ClusterRoleBinding for monitoring perms
- Add MCO and CVO related config excludes
- adapt prometheusrule to only alert on currently existing nodes
> Release v0.1.19

- Makefile
This ensures that pushing the bundle uses the replaced $TAG instead of 'latest'.
> Makefile: Make image bundle depend on $TAG

- cmd/manager/daemon.go
- cmd/manager/daemon_util.go
- pkg/controller/fileintegrity/config_defaults.go
- tests/e2e/e2e_test.go
- tests/e2e/helpers.go
Related to https://github.com/ostreedev/ostree/pull/2453, this moves the
aide.reinit file to /run (under hostroot) to avoid a possible race condition on
node shutdown.
https://github.com/openshift/file-integrity-operator/issues/211
@jhrozek @JAORMX
> Bug 2033311: Move aide.reinit to /run

- pkg/controller/fileintegrity/cm_to_fi_mapper.go
- pkg/controller/fileintegrity/fileintegrity_controller.go
- tests/e2e/e2e_test.go
- tests/e2e/helpers.go
When upgrading from much older versions, the AIDE configMaps that correspond to
FileIntegrity instances were left without an owner label, and this broke
re-inits. Fix this by re-creating the configMaps if they are found without the
owner label.
> Bug 2049206: Re-create AIDE configMaps with missing owner

- Makefile
- README.md
Previously, we used a single makefile target for doing a release (e.g.,
`make release`). This works well, but we started using a multi-step
process in the compliance-operator [0] that prepares the release and
gives the person proposing the release an opportunity to review the
release details before pushing them to the repository. This helps catch
issues before we change details of the upstream repository that could
impact how the code is consumed.
[0] https://github.com/openshift/compliance-operator/blob/master/doc/contributor.md#proposing-releases
> Break apart the make target for release

- pkg/common/constants.go
- pkg/controller/fileintegrity/fileintegrity_controller.go
Previously when enforcing the default configMap script contents, we compared
the wrong data keys. This led to the aide-reinit script not being updated
properly on an operator upgrade.
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=2072058
> Bug 2072058: Use correct data keys for script configMaps

- tests/e2e/helpers.go
When running the e2e tests repeatedly, it's possible to hit github's
rate limit. Using an image from quay.io should work around the issue.
Since the prometheus project seems to be actively updating their busybox
image, let's use that one instead of importing and then not maintaining
our own.
> tests: Use busybox from quay to work around dockerhub's rate limit

- Makefile
By default, our tests don't clean up after themselves which is a good
default. However, when iterating on tests, it might be irritating to
have to clean up manually each time, so let's expose that option as an
environment variable.
Jira: [CMP-1420](https://issues.redhat.com//browse/CMP-1420)
> tests: Expose -skipCleanupOnError as an env variable

- Makefile
Before, we assumed `origin` always pointed to the upstream repository
for the operator (openshift/file-integrity-operator). This might not be
the case if someone sets `origin` to their own fork and uses `upstream`
to point to openshift/file-integrity-operator.
Either way, we can generalize the git push commands to use an
absolute-like reference for the remote.
Fixes #246
> Use an absolute git reference for the upstream repository

- Makefile
This was a bad copy/pasta from my SSH settings. Fix it so that the
remote host is correct and uses github.com.
> Fix bad remote URL

- cmd/manager/operator.go
According to style guide
https://github.com/openshift/enhancements/blob/master/enhancements/monitoring/alerting-consistency.md#style-guide
an alert should set namespace label to identify which component is raising
the alert however NodeHasIntegrityFailure is not setting namespace label:
https://github.com/openshift/file-integrity-operator/blob/master/cmd/manager/operator.go#L266
rhbz: #2101393
> bug 2101393: operator: Set namespace label for alert

- Makefile
- bundle/manifests/file-integrity-daemon_rbac.authorization.k8s.io_v1_clusterrole.yaml
- bundle/manifests/file-integrity-daemon_rbac.authorization.k8s.io_v1_rolebinding.yaml
- config/rbac/daemon_role.yaml
- config/rbac/daemon_rolebinding.yaml
- config/rbac/kustomization.yaml
Fixes permissions for an OLM install when installing into a namespace other
than openshift-file-integrity.
- Remove the daemon RoleBinding from kustomize under config/rbac. This avoids
adding an openshift-file-integrity namespace to the subject SA during bundle
creation.
- Change the daemon Role to a ClusterRole
ref: https://bugzilla.redhat.com/show_bug.cgi?id=2104897
> Bug 2104897: Use ClusterRole and local RoleBinding for daemon permissions

- README.md
I was curious about the default during the last release I did and figure
that this would be a good thing to add directly to the release
documentation.
> Clarify the image repository used by default in the release process

- Makefile
Since the default build directory is "build", the $(BUILD_DIR) target
triggered an override warning.
Makefile:310: warning: overriding recipe for target 'build'                                                                                                                                                                            
Makefile:238: warning: ignoring old recipe for target 'build'
This removes the $(BUILD_DIR) target since ./build is part of the git
tree and should not need to be created prior to other targets.
> Makefile: Fix build dir recipe override

- tests/e2e/e2e_test.go
- tests/e2e/helpers.go
Also only modify and check on a single node, to help speed things up.
> e2e: Use pod instead of ds for logcompress file toucher

- bundle/manifests/file-integrity-daemon_rbac.authorization.k8s.io_v1_role.yaml
- bundle/manifests/file-integrity-daemon_rbac.authorization.k8s.io_v1_rolebinding.yaml
- config/rbac-daemon/daemon_rolebinding.yaml
- config/rbac/daemon_role.yaml
Moving the daemon Role to a ClusterRole as part of the fix for 2104897
was unnecessary and broke OLM upgrades.
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2108475
> Bug 2108475: Change daemon RBAC back to Role

- README.md
- tests/e2e/e2e_test.go
- tests/e2e/helpers.go
- tests/framework/framework.go
- Add `TEST_BUNDLE_INSTALL` env variable that makes the e2e suite skip initialization of the cluster and operator resources for each test case. This allows running the e2e suite against an existing deployment in a single namespace (such as an OLM install) when used together with `TEST_WATCH_NAMESPACE` and `TEST_OPERATOR_NAMESPACE`.
- Add a test case cleanup step to kill the operator pod when `TEST_BUNDLE_INSTALL` is used. This resets the metrics counter for subsequent tests.
Test with:
```
$ make catalog-deploy
$ TEST_BUNDLE_INSTALL=1 TEST_WATCH_NAMESPACE=openshift-file-integrity TEST_OPERATOR_NAMESPACE=openshift-file-integrity make e2e
```
ref: https://github.com/openshift/release/pull/30613
fixes: https://github.com/openshift/file-integrity-operator/issues/269
> e2e: Allow running against an existing deployment

- bundle/manifests/file-integrity-operator.clusterserviceversion.yaml
This is to include the permission updates from be830f7 into the CSV. Normally we do this during the release; doing it before that makes sure these permissions are included for the bundle-ci jobs. 
ref: https://github.com/openshift/release/pull/31464
@rhmdnd @jhrozek PTAL. We'll override the bundle jobs on this PR as well.
> Generate bundle

- cmd/manager/operator.go
- Run the controller-runtime metrics (controller workload stats) on port 8383.
- Remove the service endpoint for http-metrics. This was previously an additional metrics endpoint provided by operator-sdk, but was only useful for proxy programs. controller-runtime now only provides controller workqueue metrics.
- Ensure the metrics service is updated on operator startup. In turn this will update the ServiceMonitor for new changes to the service endpoints.
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2115821
> Bug 2115821: Fix controller metrics port

- README.md
- config/crd/bases/fileintegrity.openshift.io_fileintegrities.yaml
- pkg/apis/fileintegrity/v1alpha1/fileintegrity_types.go
This PR updates the default daemonset toleration to also include infra nodes.
With FedRAMP clusters using ROSA exclusively, we noticed that the AIDE daemonset pods were not spinning up on infra nodes. Looks like the default setting for tolerations is only configured for master nodes, but ROSA also has a similar taint configured on infra nodes as well. 
```shell
$ oc describe nodes -l node-role.kubernetes.io/infra | grep Taint
Taints:             node-role.kubernetes.io/infra:NoSchedule
Taints:             node-role.kubernetes.io/infra:NoSchedule
```
We've fixed our issue by adding it to the `FileIntegrity` CR we deploy via OLM but I thought it might be good to update the default for other customers who may use FIO outside of FedRAMP. Chances are if a customer is leveraging FIO for their …
> Updates AIDE Daemonset default tolerations to account for ROSA infra nodes

- .gitignore
The operator-sdk generates files for end-to-end testing and puts them in
tests/_setup. We don't need to track these in the repository, so let's
ignore them.
> Ignore generated setup files for end-to-end tests

- Makefile
We use catalog, not index these days. The variable was confusing.
> make: Remove unused variable

- CHANGELOG.md
- Makefile
This commit ensures we can install kustomize using golang 1.18 by using
v4 and using `go install`.
We needed to do something similar for other operators.
https://github.com/ComplianceAsCode/compliance-operator/issues/145
Fixes #287
> Use go-install to fetch kustomize

- CHANGELOG.md
- Makefile
Previously, we'd only tag the latest version of the operator we're
releasing in the upstream images available through
quay.io/file-integrity-operator.
In addition to the version tag (e.g., 0.1.31), we can also tag the
latest build with the `latest` tag, making it easier for users to deploy
the latest version of the upstream operator.
> Fix make release-images to properly tag `latest`

- cmd/manager/operator.go
Check against changing the Service's clusterIP, and retain the existing value as OCP 4.6 does not tolerate that. Later versions just ignore the field.
(same fix as https://github.com/ComplianceAsCode/compliance-operator/commit/404483b5b1e0c5519da5ea89c6d68baecd2b1140)
> Fix deployment on OCP 4.6

- Makefile
The SDK-aligned version of OPM was too old for the file-based catalog commands. This sets the OPM version to download locally to 1.20.0.
> Makefile: Update OPM version to 1.20.0

- Makefile
Some downstream machinery depends on the ocp-0.1 branch. Let's make sure
we sync the branch with the latest release during the `push-release`
process.
This is consistent with how we maintain the `ocp-0.1` branch in the
Compliance Operator.
> Ensure we update the ocp-0.1 branch when releasing

- Makefile
This commit needs to merge before we release a 1.0.0 release and ensures
the OpenShift release align with the appropriate upstream releases.
> Update OCP release branch

- Makefile
We need to keep track of the version number in preamble.json for the
operator index image.
Let's make sure we add it to the makefile targets for releasing the
operator so that it's included in the release commit.
> Add preamble.json to release targets

- CHANGELOG.md
- README.md
- bundle/manifests/fileintegrity.openshift.io_fileintegrities.yaml
- config/crd/bases/fileintegrity.openshift.io_fileintegrities.yaml
- pkg/apis/fileintegrity/v1alpha1/fileintegrity_types.go
- pkg/controller/fileintegrity/fileintegrity_controller.go
- tests/e2e/e2e_test.go
- tests/e2e/helpers.go
We added `initialDelay` option to FileIntegrity CRD to allow users to specify the initial delay before the first scan is run. This is useful for environments where the operator is deployed before the cluster is fully ready.
Launch of aide demonset will be delayed according to the value of initialDelay set in FileIntegrity Object.
To launch a FileIntegrity Check for worker nodes with a delay of 100s you can create the following object:
```yaml
apiVersion: fileintegrity.openshift.io/v1alpha1
kind: FileIntegrity
metadata:
name: worker-fileintegrity
namespace: openshift-file-integrity
spec:
nodeSelector:
node-role.kubernetes.io/worker: ""
config:
initialDelay: 100
```
> Add initialDelay

- build/Dockerfile
We have a separate Dockerfile used for building container images during
the release process, which is separate from the Dockerfile we use for CI
(Dockerfile.ci).
We recently updated the version of golang we use to 1.19 by updating
go.mod and the Dockerfile.ci file. But, we didn't update the golang
version for the builds we use during the upstream release process.
I caught this issue as I prepared the 1.2.0 release and noticed failures
building the new container images for that version.
This commit updates the golang version in build/Dockerfile to be
consistent with the version use in the rest of the project.
> Update golang version in Dockerfile for builds

- Makefile
We recently bumped our version of go to 1.19, but we also need to bump
our operator-sdk version to a version that is compatible with go 1.19.
While not doing this doesn't necessarily cause issues. It's to keep versions of golang
used in different parts of the project in sync.
> Bump operator-sdk from 1.15.0 to 1.27.0

- Makefile
- utils/git-remote.sh
Some contributors use different naming conventions and protocols for
their upstream and downstream branchs. Instead of assuming the same
setup for everyone, let's use a script to find which remote name to use
based on the organization and repository, and then call that script from
the release targets.
This makes the release process a little easier for contributors,
regardless of how they have their remotes setup.
> Use remote detection in release process

- Dockerfile.ci
This changes accompanies CI changes to start using OpenShift 4.13 with
RHEL 9 base images.
https://github.com/openshift/release/pull/37184
We want to start testing FIO using RHEL 9 because it relies on AIDE to
detect file system changes. We need to make sure we don't have any
regressions using RHEL 9.
> Update CI to use RHEL 9 and OpenShift 4.13

- pkg/controller/fileintegrity/config_defaults.go
We want to exclude the Kubelet CA file from the default config, so the user does not have to reinit the aide database when the cert gets renewed.
Link to the Jira Issue: [OCPBUGS-14348](https://issues.redhat.com/browse/OCPBUGS-14348)
> OCPBUGS-14348 Change the default config file to exclude kubelet CA

- tests/e2e/helpers.go
The end-to-end tests have a utility that helps assert metrics exist in
the output from the metrics endpoint. This assertion also tracks metric
errors as a slice, and then outputs them before failing the test if the
assertion fails.
However, the current logging only outputs the slice index as it iterates
over the errors, resulting in the follow output in CI failures:
helpers.go:1887: 0
helpers.go:1887: 1
helpers.go:1887: 2
helpers.go:1887: 3
While we can see something failed, it's not as useful as the actual
value, which is an Error that's more descriptive of the failure.
This commit adjusts the iteration to emit the error instead of the
index.
> Fix metric test logging

- Dockerfile.ci
- build/Dockerfile
FIO makes some assumption about aide configuration. Newer version of
aide have backwards incompatible changes with older configurations that
FIO is using, causing issues with CI. We will need to handle the
configuration migration in the operator to allow for smooth migration.
This commit pins the version of aide we're using to 0.16.0 for now until
we can handle the configuration migration and use a newer version of
aide.
Fixes #396
> Pin aide version to 0.16.0

- Makefile
Add Make command to remove all unused containers, images, pods and networks.
Sometimes the build may end up using a cached stale image for no apparent reason.
This command facilitates purging images used to build the operator and pulling fresh images.
> Add clean-images command to purge build env

- pkg/controller/status/status_controller.go
This patch removes FileIntegrityNodeStatus objects regardless of their status since the failed checks will be saved in the config map.
> OCPBUGS-15090 remove leftover nodestatus

- pkg/controller/fileintegrity/config_defaults.go
Machine config operator uses files on the host to cache annotations. The
file integrity operator will throw integrity errors if a new node is
spun up and added to the cluster depending.
Since OpenShift's MCO is responsible for these files, let's exclude them
from integrity checks like we do other MCO configuration files.
> OCPBUGS-17129: Ignore MCO node annotation files

- .github/dependabot.yml
This is the recommended approach for updating related dependencies, which results in less dependency PRs and reduces the liklihood of dependency patches getting wedged in CI.
https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/
> dependabot: Use dependabot groups to group k8s updates together

- pkg/controller/fileintegrity/fileintegrity_controller.go
This PR fixes issues on CSI driver relying on multipath, we need to set MountPropagation to HostToContainer to address this issue.
[OCPBUGS-14947](https://issues.redhat.com/browse/OCPBUGS-14947)
> OCPBUGS-14947: Fix hostmount propagation

- tests/e2e/e2e_test.go
- tests/e2e/helpers.go
Change the how we check if a kubelet cert rotation is being completed, and make sure FIO object pass after the rotation
> Fix TestFileIntegrityCertRotation e2e test

- tests/framework/framework.go
This is pretty much
https://github.com/fluxcd/flux2/commit/aa65589391db2433691d8cebde5c77c090cae3a9
reused.
The new controller-runtime version requires that the logger is set or
else there's a stack trace printed. Since even the original code doesn't
use any logger for tests, let's just use null logger with the new
version as well.
> tests: Set logger to an empty sink in tests

- cmd/manager/operator.go
- pkg/controller/metrics/metrics.go
- tests/e2e/e2e_test.go
- tests/e2e/helpers.go
In order to address CVE-2023-44487, we need to disable the http2 by default in webhook.
> Disable http2 as default for webhook

- Makefile
Implement an environment variable that we can use to pass additional
arguments into the build process. This is useful for folks that want to
build the operator in specific ways (e.g., FIPS enabled).
> Implement build flags

- Dockerfile.ci
- build/Dockerfile
Newer versions of Fedora have AIDE 0.18, which breaks with FIO due to
backwards incompatible configuration changes with AIDE 0.18.
This commit uses an older version of fedora so we can still build FIO
until integrate a newer version of AIDE.
> Use Fedora 37 for AIDE 0.16

- config/crd/bases/fileintegrity.openshift.io_fileintegrities.yaml
- config/crd/bases/fileintegrity.openshift.io_fileintegritynodestatuses.yaml
Makefile tooling is generating manifests with older kubebuilder
versions. Let's just update these so they're up-to-date with the version
we're using.
> Update manifests for kubebuilder version

- pkg/controller/fileintegrity/config_defaults.go
- tests/e2e/helpers.go
We are going to exlucde following in the default aide conf: 
`!/hostroot/etc/cni/multus/certs` for the OVN-Kubernetes CNI
`!/hostroot/etc/kubernetes/compliance-operator` for the Compliance Operator check runtime kubeletconfig `!/hostroot/etc/kubernetes/node-feature-discovery` for the Node Feature Discovery Operator
https://issues.redhat.com/browse/OCPBUGS-31257
> OCPBUGS-31257: Exclude additional files in default aide conf

- pkg/common/util.go
- tests/e2e/e2e_test.go
- tests/e2e/helpers.go
This changes prevent all node reinit when reint-on-failed is being used.
[OCPBUGS-18933](https://issues.redhat.com/browse/OCPBUGS-18933)
> OCPBUGS-18933: Fix reint-on-failed issues

- pkg/controller/fileintegrity/config_defaults.go
We're noticing some issues in CI where tests time out because node never
reach their desired state. We've also noticed MCO making changes to a
file that was previously monitored, causing failures we weren't
expecting.
This commit attempts to fix the issue by excluding the MCO file in
question so it stops raising false negative results in the e2e suite.
> Exclude MCO registry secret from integrity checks

- Makefile
- config/manager/deployment.yaml
- config/openshift-bundle/kustomization.yaml
- config/openshift-bundle/manager_patch.yaml
- tests/e2e/helpers.go
- tests/framework/context.go
- tests/framework/framework.go
- **Only set node selectors for OpenShift deployments**
- **[CMP-2624](https://issues.redhat.com//browse/CMP-2624): Implement support for running e2e tests on ROSA**
> implement rosa hcp e2e testing

- Dockerfile.AIDE0.18.ci
- pkg/controller/fileintegrity/config_defaults.go
- pkg/controller/fileintegrity/fileintegrity_controller.go
- tests/e2e/e2e_test.go
- tests/e2e/helpers.go
This PR adds the dockerfile that builds operator image with the AIDE 0.18, also replacing 0.16 config file with the 0.18 conf file using the migration logic depends on value of AIDE_VERSION. We will use 0.16 as default value if not set. This is for us to have CI to test AIDE config.
We will need to merge this one and test on https://github.com/openshift/release/pull/54911
> AIDE 0.18 e2e

- Dockerfile.AIDE0.18.ci
We are adding a missing `\` in the aide 0.18 dockerfile.
> Fix a missing back slash in aide0.18 dockerfile

- tests/e2e/helpers.go
We can shorten the run time of this particular test by not waiting as
long for the operator to install.
> Reduce initial install delay in e2e

- tests/e2e/e2e_test.go
We're seeing several tests fail with the following:
ERROR: nodes weren't in good state: status.nodeStatus for node ip-10-0-30-92.us-west-2.compute.internal NOT SUCCESS: But instead Failed
This commit increases the timeout from 5 and 10 minutes to 15 minutes so
that the nodes have more time to report back successfully.
> Increase e2e timeout for checking node success

- bundle/manifests/file-integrity-operator.clusterserviceversion.yaml
This makes it so that the replace logic also replaces the deployment
image in addition to the related image. This is necessary CI to work
properly, because it needs to be able to replace all images in the CSV
with a build from CI.
> Use latest in the CSV instead of a version tag

- .tekton/file-integrity-operator-push.yaml
Whenever an operator build on push events is successful the PULLSPEC reference in update_csv.py will be updated.
> Annotate the file to nudge after operator builds

- Makefile
- hack/tree-status
We don't have any CI that checks to make sure the bundle stays
up-to-date with PRs that may be changing the bundle. This usually
results in dirty local builds because running `make bundle` will
generate new bundles from what is kept in source based on other parts
othe project, or the operator-sdk version.
This commit adds in a target to run the `bundle` and then verify there
haven't been any changes. We can wire this up to CI to make it easier to
catch bundle changes sooner.
> Add a Makefile target to verify bundles

- tests/e2e/e2e_test.go
- tests/e2e/helpers.go
Increase a few more timeouts based on testing results.
- https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_file-integrity-operator/598/pull-ci-openshift-file-integrity-operator-master-e2e-aws/1852349359656538112
- https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_file-integrity-operator/589/pull-ci-openshift-file-integrity-operator-master-e2e-aws/1852323147982835712
- https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_file-integrity-operator/584/pull-ci-openshift-file-integrity-operator-master-e2e-aws/1852315083271573504
> Extend a few more timeout limits

- pkg/controller/configmap/configmap_controller.go
- pkg/controller/metrics/metrics.go
- tests/e2e/e2e_test.go
- tests/e2e/helpers.go
The metric `file_integrity_operator_node_failed` was being reset after the File Integrity Operator pod restarted, causing the `NodeHasIntegrityFailure` alert to clear despite failures persisting in `fileintegritynodestatuses`. This fix ensures that the operator retrieves the status of existing node failures and re-triggers the alert as needed, maintaining consistency in node failure detection.
> OCPBUGS-42807: Preserve metrics when pod crashes

- bundle.openshfit.Dockerfile
- bundle/manifests/file-integrity-operator.clusterserviceversion.yaml
- catalog/preamble.json
- config/manifests/bases/file-integrity-operator.clusterserviceversion.yaml
- version.Makefile
- version/version.go
This will allow us to differentiate the upstream builds from latest released version and the next version.
> Bump version to 1.3.5-dev

- pkg/controller/fileintegrity/fileintegrity_controller.go
`/etc/kubernetes/static-pod-resource` is being created after a new node is added, this cause the link count change in the aide checks and resulting a failures. The PR added a init pod to check for that before running aide daemonset.
> OCPBUGS-36483: Fix new added node issue

- pkg/common/util.go
This commit resolves issues in `GetRemovedNodeHoldoffAnnotation` and `GetAddedNodeHoldoffAnnotation` related to managing the holdoff annotation for `FileIntegrity` Object. Previously, node removal could fail in cases where the node to be removed was at the beginning, middle, or end of a comma separated list due to incorrect string manipulation.
> OCPBUGS-37300: Fix forced reinit issue

- bundle-hack/update_csv.go
This commit updates the bundle build scripts so that it references
images in registry.redhat.io, so that the bundle image will work once
it's released. The images won't resolve, and we will use an
ImageContentSourcePolicy to replace the image requests to
registry.redhat.io with the quay.io references maintained by Konflux.
The important part here is that we're using the same SHA as what's
proposed in quay.io, so that when the image is mirrored the reference
will resolve.
> CMP-3362: Update bundle images for Red Hat registries

- .tekton/file-integrity-operator-bundle-push.yaml
We only really need to build the bundle image when the operator image
reference changes, or if the build pipline configuration change for the
bundle build.
> CMP-3381: Update the bundle pipeline to only run for specific changes

- .tekton/file-integrity-operator-push.yaml
https://github.com/openshift/file-integrity-operator/pull/598 refactored
the update_csv.py to update_csv.go. This commit updates the nudge to
account for that so we can have Konflux propose image updates
automatically.
> CMP-3381: Configure Konflux to bump image SHAs

- bundle-hack/update_csv.go
Make sure we're building bundle images that reference the latest FIO
operator image for 1.3.6.
> CMP-3381: Update operator image reference

- Dockerfile.ci
- Makefile
- build/Dockerfile
- build/Dockerfile.openshift
- build/guard/libaide_md5_guard.c
- cmd/manager/daemon_util.go
- konflux/rpms.lock.yaml
- pkg/common/util.go
This update introduces an LD_PRELOAD-based guard library to block MD5 usage by AIDE in FIPS mode, enforcing strict compliance independently of AIDE’s internal error handling. The Makefile and build scripts now build and package this guard, injecting it during AIDE database initialization. Enhanced error handling clearly identifies guard-triggered terminations as FIPS compliance errors.
This ensures robust FIPS enforcement, eliminating accidental MD5 use by AIDE.
Background:
• [Red Hat FIPS Compliance](https://access.redhat.com/compliance/fips?extIdCarryOver=true&sc_cid=701f2000001Css5AAC)
From libgcrypt-1.10.0-10 onward, MD5 and other non-FIPS algorithms no longer fail automatically. A new FIPS service indicator API (GCRYCTL_FIPS_SERVICE_INDICATOR_MD) classifies algorithms as approved …
> OCPBUGS-56409: Fix FIPS for aide container

- bundle-hack/update_csv.go
Since we now have a separate pipeline for the 1.3 releases, we need to update the image digest to use the image built from that pipeline in the bundle image. Otherwise, we're going to be using the operator image built from master.
> Update digest for operator image

- .tekton/file-integrity-operator-bundle-master-push.yaml
- .tekton/file-integrity-operator-bundle-push.yaml
- .tekton/file-integrity-operator-master-push.yaml
- .tekton/file-integrity-operator-push.yaml
By adding the branch name to the most recent builds on push events
through Konflux, we can make it easier to fetch the latest builds on a
given branch. For example, we can fetch them using the `master` tag or
the latest 1.3 release candidate using `release-1.3` for both the bundle
and the operator.
Adding this tag makes it easier to fetch the latest images from other
locations, like the FBC repository where we need to find the digest to
build the appropriate index image.
> Update pipeline runs to include branch name as image tag

- build/guard/libaide_md5_guard.c
- cmd/manager/daemon_util.go
- pkg/controller/fileintegrity/fileintegrity_controller.go
Instead of hard exist the program, we will disable the AIDE on FIPS mode without failing the AIDE program in most cases, so AIDE will run without the MD5
```
sh-5.1# LD_PRELOAD=/opt/libaide_md5_guard.so aide -i ; echo $? [md-guard] Attempt to enable MD5 in FIPS — soft block gcry_md_enable 1 failed
Start timestamp: 2025-05-29 07:35:03 +0000 (AIDE 0.16) AIDE initialized database at /var/lib/aide/aide.db.new.gz
Number of entries:      2845
--------------------------------------------------- The attributes of the (uncompressed) database(s):
---------------------------------------------------
/var/lib/aide/aide.db.new.gz
SHA1     : XKhXEl5aBIIrGKayqdKt9lNVL+0=
SHA256   : GkEwcPjSe9XItfcYBF3/U3xF040Pt4ay
SfBqOomyyQc=
SHA512   : 2FXAGkolRaVqx6WpMxM4uAaK5uMGMPuB
Unu0CuIh5mRLHTCEKIKfTeij0c1fbdzx …
```
> Block MD5 without failing AIDE

- build/guard/libaide_md5_guard.c
- cmd/manager/daemon_util.go
- pkg/controller/fileintegrity/fileintegrity_controller.go
Instead of hard exist the program, we will disable the AIDE on FIPS mode without failing the AIDE program in most cases, so AIDE will run without the MD5
```
sh-5.1# LD_PRELOAD=/opt/libaide_md5_guard.so aide -i ; echo $? [md-guard] Attempt to enable MD5 in FIPS — soft block gcry_md_enable 1 failed
Start timestamp: 2025-05-29 07:35:03 +0000 (AIDE 0.16) AIDE initialized database at /var/lib/aide/aide.db.new.gz
Number of entries:      2845
--------------------------------------------------- The attributes of the (uncompressed) database(s):
---------------------------------------------------
/var/lib/aide/aide.db.new.gz
SHA1     : XKhXEl5aBIIrGKayqdKt9lNVL+0=
SHA256   : GkEwcPjSe9XItfcYBF3/U3xF040Pt4ay
SfBqOomyyQc=
SHA512   : 2FXAGkolRaVqx6WpMxM4uAaK5uMGMPuB
Unu0CuIh5mRLHTCEKIKfTeij0c1fbdzx …
```
> backport Block MD5 without failing AIDE

- .github/workflows/gosec.yaml
Let's make sure we're using gosec findings in our review process to
catch issues early, before they land in the codebase.
> CMP-3441: Add a github action for gosec

- build/Dockerfile.openshift
Add a `license` directory to the operator image.
This abides to test `HasLicense` from Image Contents Requirements:
https://docs.redhat.com/en/documentation/red_hat_software_certification/2025/html-single/red_hat_openshift_software_certification_policy_guide/index#con-image-content-requirements_openshift-sw-cert-policy-container-images
> Add licenses dir with operator LICENSE

- .tekton/file-integrity-operator-bundle-release-1-3-pull-request.yaml
- .tekton/file-integrity-operator-bundle-release-1-3-push.yaml
- .tekton/file-integrity-operator-release-1-3-pull-request.yaml
- .tekton/file-integrity-operator-release-1-3-push.yaml
Only run bundle pipelines when there are changes to bundle relevant files.
> Make bundle pipelines runs more restricted

- bundle-hack/update_csv.go
Let's reference the latest image operator in the bundle image.
- Last merged PR: https://github.com/openshift/file-integrity-operator/pull/739
- Commit that triggered the event: https://konflux-ui.apps.kflux-prd-rh02.0fk9.p1.openshiftapps.com/ns/ocp-isc-tenant/applications/file-integrity-operator-release-1-3/commit/c3787af07a461b9e44581194cd3143fc1c2a6d76
- Push pipeline: https://konflux-ui.apps.kflux-prd-rh02.0fk9.p1.openshiftapps.com/ns/ocp-isc-tenant/applications/file-integrity-operator-release-1-3/pipelineruns/file-integrity-operator-release-1-3-on-push-l9dvn
> Nudge the bundle build after #739

- .tekton/file-integrity-operator-dev-push.yaml
The default value of `".*Dockerfile.*, .*.yaml, .*Containerfile.*"` doesn't suit us.
> Configure file to nudge after builds

- .tekton/file-integrity-operator-bundle-dev-pull-request.yaml
- .tekton/file-integrity-operator-bundle-dev-push.yaml
- .tekton/file-integrity-operator-dev-pull-request.yaml
- .tekton/file-integrity-operator-dev-push.yaml
- Configure our pipelines to send reports back to Snyk dashboard
> CMP-3539: Configure sast-snyk-check to upload reports to our org
